"""baseline: create all tables from models

Revision ID: 157247e0df86
Revises:
Create Date: 2026-03-29 01:22:53.579213

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "157247e0df86"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource", sa.String(length=255), nullable=False),
        sa.Column("old_value_hash", sa.String(length=64), nullable=True),
        sa.Column("new_value_hash", sa.String(length=64), nullable=True),
        sa.Column("user_metadata", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_resource"), "audit_logs", ["resource"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_email"), "audit_logs", ["user_email"], unique=False)
    op.create_table(
        "config_overrides",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=2000), nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_config_overrides_key"), "config_overrides", ["key"], unique=True)
    op.create_table(
        "graph_memory",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("graph_data", sa.JSON(), nullable=False),
        sa.Column("total_nodes", sa.Integer(), nullable=False),
        sa.Column("total_edges", sa.Integer(), nullable=False),
        sa.Column("avg_edge_weight", sa.Float(), nullable=False),
        sa.Column("max_edge_weight", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_decay_at", sa.DateTime(), nullable=True),
        sa.Column("last_consolidation_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graph_memory_user_id"), "graph_memory", ["user_id"], unique=True)
    op.create_table(
        "mcp_tool_descriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tool_name", sa.String(length=50), nullable=False),
        sa.Column("locale", sa.String(length=10), server_default="en", nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_mcp_tool_descriptions_tool_locale",
        "mcp_tool_descriptions",
        ["tool_name", "locale"],
        unique=True,
    )
    op.create_index(
        op.f("ix_mcp_tool_descriptions_tool_name"),
        "mcp_tool_descriptions",
        ["tool_name"],
        unique=False,
    )
    op.create_table(
        "neural_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("value_type", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_neural_config_category"), "neural_config", ["category"], unique=False)
    op.create_index(op.f("ix_neural_config_key"), "neural_config", ["key"], unique=True)
    op.create_table(
        "oauth_authorization_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("redirect_uri", sa.String(length=512), nullable=False),
        sa.Column("scope", sa.String(length=255), nullable=True),
        sa.Column("code_challenge", sa.String(length=128), nullable=True),
        sa.Column("code_challenge_method", sa.String(length=10), nullable=True),
        sa.Column("resource", sa.String(length=512), nullable=True),
        sa.Column("auth_time", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_oauth_codes_client_user",
        "oauth_authorization_codes",
        ["client_id", "user_id"],
        unique=False,
    )
    op.create_index(
        "idx_oauth_codes_resource", "oauth_authorization_codes", ["resource"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_authorization_codes_client_id"),
        "oauth_authorization_codes",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_authorization_codes_code"),
        "oauth_authorization_codes",
        ["code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_oauth_authorization_codes_expires_at"),
        "oauth_authorization_codes",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_authorization_codes_user_id"),
        "oauth_authorization_codes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "resource_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("op", sa.String(length=10), nullable=False),
        sa.Column("doc_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "event_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
        ),
        sa.Column("importance", sa.Float(), server_default="0.6", nullable=False),
        sa.CheckConstraint("op IN ('upsert', 'delete')", name="check_op_type"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_resource_events_created_at"), "resource_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_resource_events_resource_id"), "resource_events", ["resource_id"], unique=False
    )
    op.create_table(
        "resource_schemas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("field_definitions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resource_schemas_resource_id"), "resource_schemas", ["resource_id"], unique=False
    )
    op.create_table(
        "resource_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quota_events_per_hour", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_resource_tokens_resource_id"), "resource_tokens", ["resource_id"], unique=False
    )
    op.create_table(
        "user_plans",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("plan_name", sa.String(length=50), nullable=False),
        sa.Column("memory_limit", sa.Integer(), nullable=False),
        sa.Column("daily_api_limit", sa.Integer(), nullable=False),
        sa.Column("weekly_api_limit", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index("idx_user_plans_plan_name", "user_plans", ["plan_name"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_user_id", sa.String(length=255), nullable=False),
        sa.Column("plan_name", sa.String(length=50), server_default="free", nullable=False),
        sa.Column("memory_limit", sa.Integer(), server_default="1000", nullable=False),
        sa.Column("daily_api_limit", sa.Integer(), server_default="1000", nullable=False),
        sa.Column("weekly_api_limit", sa.Integer(), server_default="5000", nullable=False),
        sa.Column("addon_memory_bonus", sa.Integer(), server_default="0", nullable=False),
        sa.Column("addon_mcp_quota_bonus", sa.Integer(), server_default="0", nullable=False),
        sa.Column("addon_rest_quota_bonus", sa.Integer(), server_default="0", nullable=False),
        sa.Column("addon_public_quota_bonus", sa.Integer(), server_default="0", nullable=False),
        sa.Column("addon_member_bonus", sa.Integer(), server_default="0", nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("plan_name IN ('free', 'basic', 'pro')", name="valid_plan_name"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspaces_owner_user_id"), "workspaces", ["owner_user_id"], unique=False
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("hidden_at", sa.DateTime(), nullable=True),
        sa.Column("visibility_expires_at", sa.DateTime(), nullable=True),
        sa.Column("plaintext_encrypted", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_expires", "api_keys", ["expires_at"], unique=False)
    op.create_index("idx_revoked", "api_keys", ["revoked_at"], unique=False)
    op.create_index("idx_user_name", "api_keys", ["user_id", "name"], unique=False)
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_index(op.f("ix_api_keys_workspace_id"), "api_keys", ["workspace_id"], unique=False)
    op.create_table(
        "contexts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("usage_guide", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_private", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_public", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.CheckConstraint("name ~ '^[a-z0-9_-]+$'", name="valid_context_name"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contexts_workspace_id"), "contexts", ["workspace_id"], unique=False)
    op.create_table(
        "oauth_clients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=False),
        sa.Column("client_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("client_name", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("redirect_uris", sa.JSON(), nullable=False),
        sa.Column("grant_types", sa.JSON(), nullable=False),
        sa.Column("response_types", sa.JSON(), nullable=False),
        sa.Column("scope", sa.String(length=255), nullable=False),
        sa.Column("token_endpoint_auth_method", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("hidden_at", sa.DateTime(), nullable=True),
        sa.Column("visibility_expires_at", sa.DateTime(), nullable=True),
        sa.Column("plaintext_secret_encrypted", sa.String(), nullable=True),
        sa.Column("provider", sa.String(length=50), server_default="custom", nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oauth_clients_client_id"), "oauth_clients", ["client_id"], unique=True)
    op.create_index(op.f("ix_oauth_clients_owner_id"), "oauth_clients", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_oauth_clients_workspace_id"), "oauth_clients", ["workspace_id"], unique=False
    )
    op.create_table(
        "plan_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("old_plan", sa.String(length=20), nullable=True),
        sa.Column("new_plan", sa.String(length=20), nullable=False),
        sa.Column("changed_by", sa.String(length=255), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("old_memory_limit", sa.Integer(), nullable=True),
        sa.Column("old_daily_api_limit", sa.Integer(), nullable=True),
        sa.Column("old_weekly_api_limit", sa.Integer(), nullable=True),
        sa.Column("new_memory_limit", sa.Integer(), nullable=True),
        sa.Column("new_daily_api_limit", sa.Integer(), nullable=True),
        sa.Column("new_weekly_api_limit", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_plan_changes_changed_by", "plan_changes", ["changed_by"], unique=False)
    op.create_index(
        "idx_plan_changes_date",
        "plan_changes",
        ["changed_at"],
        unique=False,
        postgresql_ops={"changed_at": "DESC"},
    )
    op.create_index("idx_plan_changes_workspace", "plan_changes", ["workspace_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("picture", sa.String(length=512), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_initial_admin", sa.Boolean(), nullable=False),
        sa.Column("current_workspace_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("auth_provider", sa.String(length=20), nullable=True),
        sa.CheckConstraint("role IN ('admin', 'user')", name="valid_role"),
        sa.ForeignKeyConstraint(["current_workspace_id"], ["workspaces.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_current_workspace_id"), "users", ["current_workspace_id"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_initial_admin"), "users", ["is_initial_admin"], unique=False)
    op.create_index(op.f("ix_users_locale"), "users", ["locale"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_timezone"), "users", ["timezone"], unique=False)
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=True)
    op.create_table(
        "workspace_addons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("addon_type", sa.String(length=50), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("purchase_price_cents", sa.Integer(), nullable=True),
        sa.Column("stripe_product_id", sa.String(length=100), nullable=True),
        sa.Column("active_from", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("active_until", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "addon_type IN ('extra_storage', 'extra_memory', 'extra_mcp_quota', 'extra_rest_quota', 'extra_public_quota', 'extra_members')",
            name="check_addon_type",
        ),
        sa.CheckConstraint("quantity > 0", name="check_quantity_positive"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspace_addons_workspace_id"), "workspace_addons", ["workspace_id"], unique=False
    )
    op.create_table(
        "workspace_invitations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=50), server_default="member", nullable=False),
        sa.Column("invited_by", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_by", sa.String(length=255), nullable=True),
        sa.Column("allowed_context_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member', 'viewer')", name="valid_invitation_role"
        ),
        sa.CheckConstraint("length(token) >= 20", name="valid_invitation_token"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspace_invitations_email"), "workspace_invitations", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_workspace_invitations_expires_at"),
        "workspace_invitations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_invitations_token"), "workspace_invitations", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_workspace_invitations_workspace_id"),
        "workspace_invitations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "workspace_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), server_default="member", nullable=False),
        sa.Column("allowed_context_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("invited_by", sa.String(length=255), nullable=True),
        sa.Column("invited_at", sa.DateTime(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member', 'viewer')", name="valid_workspace_member_role"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_workspace_members_org", "workspace_members", ["workspace_id"], unique=False
    )
    op.create_index(
        "idx_workspace_members_role", "workspace_members", ["workspace_id", "role"], unique=False
    )
    op.create_index("idx_workspace_members_user", "workspace_members", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_workspace_members_user_id"), "workspace_members", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_workspace_members_workspace_id"),
        "workspace_members",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "context_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), server_default="editor", nullable=False),
        sa.Column("invited_by", sa.String(length=255), nullable=True),
        sa.Column("invited_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "role IN ('owner', 'editor', 'viewer')", name="valid_context_member_role"
        ),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_context_members_context", "context_members", ["context_id"], unique=False)
    op.create_index("idx_context_members_user", "context_members", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_context_members_context_id"), "context_members", ["context_id"], unique=False
    )
    op.create_index(
        op.f("ix_context_members_user_id"), "context_members", ["user_id"], unique=False
    )
    op.create_table(
        "context_search_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("semantic_weight", sa.DECIMAL(precision=3, scale=2), nullable=False),
        sa.Column("bm25_weight", sa.DECIMAL(precision=3, scale=2), nullable=False),
        sa.Column("fetch_factor", sa.Integer(), nullable=False),
        sa.Column("use_rerank", sa.Boolean(), nullable=False),
        sa.Column("reranker_provider", sa.String(length=20), nullable=True),
        sa.Column("reranker_model", sa.String(length=50), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reranker_provider IN ('voyage', 'cohere')", name="reranker_provider_check"
        ),
        sa.CheckConstraint(
            "ABS(semantic_weight + bm25_weight - 1.0) < 0.01", name="weights_sum_check"
        ),
        sa.CheckConstraint("bm25_weight >= 0.0 AND bm25_weight <= 1.0", name="bm25_weight_range"),
        sa.CheckConstraint("fetch_factor >= 1 AND fetch_factor <= 10", name="fetch_factor_range"),
        sa.CheckConstraint(
            "semantic_weight >= 0.0 AND semantic_weight <= 1.0", name="semantic_weight_range"
        ),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_search_configs_context_id"),
        "context_search_configs",
        ["context_id"],
        unique=True,
    )
    op.create_table(
        "external_api_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key_name", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("encrypted_value", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_external_enabled",
        "external_api_keys",
        ["user_id", "provider", "enabled"],
        unique=False,
    )
    op.create_index("idx_external_updated", "external_api_keys", ["updated_at"], unique=False)
    op.create_index(
        "idx_external_user_provider", "external_api_keys", ["user_id", "provider"], unique=False
    )
    op.create_index(
        op.f("ix_external_api_keys_key_name"), "external_api_keys", ["key_name"], unique=False
    )
    op.create_index(
        op.f("ix_external_api_keys_provider"), "external_api_keys", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_external_api_keys_user_id"), "external_api_keys", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_external_api_keys_workspace_id"),
        "external_api_keys",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "indexer_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("last_offset", sa.BigInteger(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("active_version", sa.Integer(), nullable=False),
        sa.Column("job_status", sa.String(length=20), nullable=False),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "job_status IN ('idle', 'queued', 'running', 'failed')", name="check_job_status"
        ),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indexer_state_context_id"), "indexer_state", ["context_id"], unique=False
    )
    op.create_index(
        op.f("ix_indexer_state_next_run_at"), "indexer_state", ["next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_indexer_state_resource_id"), "indexer_state", ["resource_id"], unique=False
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("summary_embedding_id", sa.UUID(), nullable=True),
        sa.Column("embedding_status", sa.String(length=20), nullable=False),
        sa.Column("embedding_error", sa.Text(), nullable=True),
        sa.Column("context_summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("long_term", sa.Boolean(), nullable=False),
        sa.Column("promoted_at", sa.DateTime(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("accessed_by_clients", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column("client", sa.String(length=100), nullable=False),
        sa.Column("client_version", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "resource_id",
            sa.String(length=255),
            sa.Computed("details->>'resource_id'", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "resource_doc_id",
            sa.String(length=255),
            sa.Computed("details->>'doc_id'", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "resource_version",
            sa.Integer(),
            sa.Computed(
                "CASE WHEN details->>'version' ~ '^[0-9]+$' THEN (details->>'version')::INTEGER ELSE NULL END",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.CheckConstraint(
            "embedding_status IN ('pending', 'success', 'failed')", name="valid_embedding_status"
        ),
        sa.CheckConstraint("scope IN ('working', 'persistent')", name="valid_scope"),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="valid_confidence"),
        sa.CheckConstraint("importance BETWEEN 0 AND 1", name="valid_importance"),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_consolidation",
        "memories",
        ["user_id", "long_term", "use_count", "importance"],
        unique=False,
    )
    op.create_index(
        "idx_context",
        "memories",
        [sa.text("CAST(context -> 'context_id' AS VARCHAR)")],
        unique=False,
    )
    op.create_index("idx_created_at", "memories", ["created_at"], unique=False)
    op.create_index("idx_last_used", "memories", ["last_used_at"], unique=False)
    op.create_index("idx_user_scope", "memories", ["user_id", "scope"], unique=False)
    op.create_index("idx_user_type", "memories", ["user_id", "type"], unique=False)
    op.create_index(op.f("ix_memories_context_id"), "memories", ["context_id"], unique=False)
    op.create_index(op.f("ix_memories_scope"), "memories", ["scope"], unique=False)
    op.create_index(op.f("ix_memories_type"), "memories", ["type"], unique=False)
    op.create_index(op.f("ix_memories_user_id"), "memories", ["user_id"], unique=False)
    op.create_index(op.f("ix_memories_workspace_id"), "memories", ["workspace_id"], unique=False)
    op.create_table(
        "neural_memory_edges",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("src_id", sa.UUID(), nullable=False),
        sa.Column("dst_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.Column("edge_type", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "edge_type IN ('neural_association', 'related_to', 'depends_on', 'learned_from')",
            name="valid_edge_type",
        ),
        sa.CheckConstraint("confidence >= 0.0 AND confidence <= 1.0", name="valid_confidence"),
        sa.CheckConstraint("weight >= 0.0 AND weight <= 3.0", name="valid_weight"),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "src_id", "dst_id", name="unique_edge"),
    )
    op.create_index(
        "idx_edges_user_dst", "neural_memory_edges", ["user_id", "dst_id"], unique=False
    )
    op.create_index(
        "idx_edges_user_src", "neural_memory_edges", ["user_id", "src_id"], unique=False
    )
    op.create_index(
        op.f("ix_neural_memory_edges_context_id"),
        "neural_memory_edges",
        ["context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_neural_memory_edges_dst_id"), "neural_memory_edges", ["dst_id"], unique=False
    )
    op.create_index(
        op.f("ix_neural_memory_edges_src_id"), "neural_memory_edges", ["src_id"], unique=False
    )
    op.create_index(
        op.f("ix_neural_memory_edges_user_id"), "neural_memory_edges", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_neural_memory_edges_workspace_id"),
        "neural_memory_edges",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("token_type", sa.String(length=20), nullable=False),
        sa.Column("access_token", sa.String(length=255), nullable=False),
        sa.Column("refresh_token", sa.String(length=255), nullable=True),
        sa.Column("scope", sa.String(length=255), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("access_token_revoked_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_token_revoked_at", sa.DateTime(), nullable=True),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.Column("resource", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["oauth_clients.client_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_oauth_tokens_client_user", "oauth_tokens", ["client_id", "user_id"], unique=False
    )
    op.create_index("idx_oauth_tokens_resource", "oauth_tokens", ["resource"], unique=False)
    op.create_index(
        op.f("ix_oauth_tokens_access_token"), "oauth_tokens", ["access_token"], unique=True
    )
    op.create_index(op.f("ix_oauth_tokens_client_id"), "oauth_tokens", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_oauth_tokens_refresh_token"), "oauth_tokens", ["refresh_token"], unique=True
    )
    op.create_index(op.f("ix_oauth_tokens_revoked"), "oauth_tokens", ["revoked"], unique=False)
    op.create_index(op.f("ix_oauth_tokens_user_id"), "oauth_tokens", ["user_id"], unique=False)
    op.create_table(
        "usage_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_usage_stats_context_date", "usage_stats", ["context_id", "date"], unique=False
    )
    op.create_index("idx_usage_stats_endpoint", "usage_stats", ["endpoint", "date"], unique=False)
    op.create_index(
        "idx_usage_stats_project_date", "usage_stats", ["project_id", "date"], unique=False
    )
    op.create_index("idx_usage_stats_user_date", "usage_stats", ["user_id", "date"], unique=False)
    op.create_index(
        "idx_usage_stats_user_endpoint",
        "usage_stats",
        ["user_id", "endpoint", "date"],
        unique=False,
    )
    op.create_index(
        "idx_usage_stats_workspace_date", "usage_stats", ["workspace_id", "date"], unique=False
    )
    op.create_index(op.f("ix_usage_stats_date"), "usage_stats", ["date"], unique=False)
    op.create_index(op.f("ix_usage_stats_user_id"), "usage_stats", ["user_id"], unique=False)
    op.create_table(
        "attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "size_bytes > 0 AND size_bytes <= 5242880", name="attachment_size_limit"
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attachments_memory_id"), "attachments", ["memory_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attachments_memory_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_usage_stats_user_id"), table_name="usage_stats")
    op.drop_index(op.f("ix_usage_stats_date"), table_name="usage_stats")
    op.drop_index("idx_usage_stats_workspace_date", table_name="usage_stats")
    op.drop_index("idx_usage_stats_user_endpoint", table_name="usage_stats")
    op.drop_index("idx_usage_stats_user_date", table_name="usage_stats")
    op.drop_index("idx_usage_stats_project_date", table_name="usage_stats")
    op.drop_index("idx_usage_stats_endpoint", table_name="usage_stats")
    op.drop_index("idx_usage_stats_context_date", table_name="usage_stats")
    op.drop_table("usage_stats")
    op.drop_index(op.f("ix_oauth_tokens_user_id"), table_name="oauth_tokens")
    op.drop_index(op.f("ix_oauth_tokens_revoked"), table_name="oauth_tokens")
    op.drop_index(op.f("ix_oauth_tokens_refresh_token"), table_name="oauth_tokens")
    op.drop_index(op.f("ix_oauth_tokens_client_id"), table_name="oauth_tokens")
    op.drop_index(op.f("ix_oauth_tokens_access_token"), table_name="oauth_tokens")
    op.drop_index("idx_oauth_tokens_resource", table_name="oauth_tokens")
    op.drop_index("idx_oauth_tokens_client_user", table_name="oauth_tokens")
    op.drop_table("oauth_tokens")
    op.drop_index(op.f("ix_neural_memory_edges_workspace_id"), table_name="neural_memory_edges")
    op.drop_index(op.f("ix_neural_memory_edges_user_id"), table_name="neural_memory_edges")
    op.drop_index(op.f("ix_neural_memory_edges_src_id"), table_name="neural_memory_edges")
    op.drop_index(op.f("ix_neural_memory_edges_dst_id"), table_name="neural_memory_edges")
    op.drop_index(op.f("ix_neural_memory_edges_context_id"), table_name="neural_memory_edges")
    op.drop_index("idx_edges_user_src", table_name="neural_memory_edges")
    op.drop_index("idx_edges_user_dst", table_name="neural_memory_edges")
    op.drop_table("neural_memory_edges")
    op.drop_index(op.f("ix_memories_workspace_id"), table_name="memories")
    op.drop_index(op.f("ix_memories_user_id"), table_name="memories")
    op.drop_index(op.f("ix_memories_type"), table_name="memories")
    op.drop_index(op.f("ix_memories_scope"), table_name="memories")
    op.drop_index(op.f("ix_memories_context_id"), table_name="memories")
    op.drop_index("idx_user_type", table_name="memories")
    op.drop_index("idx_user_scope", table_name="memories")
    op.drop_index("idx_last_used", table_name="memories")
    op.drop_index("idx_created_at", table_name="memories")
    op.drop_index("idx_context", table_name="memories")
    op.drop_index("idx_consolidation", table_name="memories")
    op.drop_table("memories")
    op.drop_index(op.f("ix_indexer_state_resource_id"), table_name="indexer_state")
    op.drop_index(op.f("ix_indexer_state_next_run_at"), table_name="indexer_state")
    op.drop_index(op.f("ix_indexer_state_context_id"), table_name="indexer_state")
    op.drop_table("indexer_state")
    op.drop_index(op.f("ix_external_api_keys_workspace_id"), table_name="external_api_keys")
    op.drop_index(op.f("ix_external_api_keys_user_id"), table_name="external_api_keys")
    op.drop_index(op.f("ix_external_api_keys_provider"), table_name="external_api_keys")
    op.drop_index(op.f("ix_external_api_keys_key_name"), table_name="external_api_keys")
    op.drop_index("idx_external_user_provider", table_name="external_api_keys")
    op.drop_index("idx_external_updated", table_name="external_api_keys")
    op.drop_index("idx_external_enabled", table_name="external_api_keys")
    op.drop_table("external_api_keys")
    op.drop_index(op.f("ix_context_search_configs_context_id"), table_name="context_search_configs")
    op.drop_table("context_search_configs")
    op.drop_index(op.f("ix_context_members_user_id"), table_name="context_members")
    op.drop_index(op.f("ix_context_members_context_id"), table_name="context_members")
    op.drop_index("idx_context_members_user", table_name="context_members")
    op.drop_index("idx_context_members_context", table_name="context_members")
    op.drop_table("context_members")
    op.drop_index(op.f("ix_workspace_members_workspace_id"), table_name="workspace_members")
    op.drop_index(op.f("ix_workspace_members_user_id"), table_name="workspace_members")
    op.drop_index("idx_workspace_members_user", table_name="workspace_members")
    op.drop_index("idx_workspace_members_role", table_name="workspace_members")
    op.drop_index("idx_workspace_members_org", table_name="workspace_members")
    op.drop_table("workspace_members")
    op.drop_index(op.f("ix_workspace_invitations_workspace_id"), table_name="workspace_invitations")
    op.drop_index(op.f("ix_workspace_invitations_token"), table_name="workspace_invitations")
    op.drop_index(op.f("ix_workspace_invitations_expires_at"), table_name="workspace_invitations")
    op.drop_index(op.f("ix_workspace_invitations_email"), table_name="workspace_invitations")
    op.drop_table("workspace_invitations")
    op.drop_index(op.f("ix_workspace_addons_workspace_id"), table_name="workspace_addons")
    op.drop_table("workspace_addons")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_timezone"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_locale"), table_name="users")
    op.drop_index(op.f("ix_users_is_initial_admin"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_current_workspace_id"), table_name="users")
    op.drop_table("users")
    op.drop_index("idx_plan_changes_workspace", table_name="plan_changes")
    op.drop_index(
        "idx_plan_changes_date", table_name="plan_changes", postgresql_ops={"changed_at": "DESC"}
    )
    op.drop_index("idx_plan_changes_changed_by", table_name="plan_changes")
    op.drop_table("plan_changes")
    op.drop_index(op.f("ix_oauth_clients_workspace_id"), table_name="oauth_clients")
    op.drop_index(op.f("ix_oauth_clients_owner_id"), table_name="oauth_clients")
    op.drop_index(op.f("ix_oauth_clients_client_id"), table_name="oauth_clients")
    op.drop_table("oauth_clients")
    op.drop_index(op.f("ix_contexts_workspace_id"), table_name="contexts")
    op.drop_table("contexts")
    op.drop_index(op.f("ix_api_keys_workspace_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index("idx_user_name", table_name="api_keys")
    op.drop_index("idx_revoked", table_name="api_keys")
    op.drop_index("idx_expires", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_workspaces_owner_user_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index("idx_user_plans_plan_name", table_name="user_plans")
    op.drop_table("user_plans")
    op.drop_index(op.f("ix_resource_tokens_resource_id"), table_name="resource_tokens")
    op.drop_table("resource_tokens")
    op.drop_index(op.f("ix_resource_schemas_resource_id"), table_name="resource_schemas")
    op.drop_table("resource_schemas")
    op.drop_index(op.f("ix_resource_events_resource_id"), table_name="resource_events")
    op.drop_index(op.f("ix_resource_events_created_at"), table_name="resource_events")
    op.drop_table("resource_events")
    op.drop_index(
        op.f("ix_oauth_authorization_codes_user_id"), table_name="oauth_authorization_codes"
    )
    op.drop_index(
        op.f("ix_oauth_authorization_codes_expires_at"), table_name="oauth_authorization_codes"
    )
    op.drop_index(op.f("ix_oauth_authorization_codes_code"), table_name="oauth_authorization_codes")
    op.drop_index(
        op.f("ix_oauth_authorization_codes_client_id"), table_name="oauth_authorization_codes"
    )
    op.drop_index("idx_oauth_codes_resource", table_name="oauth_authorization_codes")
    op.drop_index("idx_oauth_codes_client_user", table_name="oauth_authorization_codes")
    op.drop_table("oauth_authorization_codes")
    op.drop_index(op.f("ix_neural_config_key"), table_name="neural_config")
    op.drop_index(op.f("ix_neural_config_category"), table_name="neural_config")
    op.drop_table("neural_config")
    op.drop_index(op.f("ix_mcp_tool_descriptions_tool_name"), table_name="mcp_tool_descriptions")
    op.drop_index("idx_mcp_tool_descriptions_tool_locale", table_name="mcp_tool_descriptions")
    op.drop_table("mcp_tool_descriptions")
    op.drop_index(op.f("ix_graph_memory_user_id"), table_name="graph_memory")
    op.drop_table("graph_memory")
    op.drop_index(op.f("ix_config_overrides_key"), table_name="config_overrides")
    op.drop_table("config_overrides")
    op.drop_index(op.f("ix_audit_logs_user_email"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
