"""Seed kagura-cli public OAuth2 client for SDK device-flow login (Issue #624).

This migration seeds ONE global public OAuth2 client used by the Kagura
Memory Python SDK (and any future first-party CLI) to drive the device
authorization grant (RFC 8628). The shape is fixed by Issue #624 review:

- ``owner_id=NULL`` — DCR-pattern, per ``d04_519_oauth_owner_nullable``.
  The workspace context is resolved at ``/device`` consent time from the
  consenting user's session (same mechanism as #519), not from the
  client record.
- ``workspace_id=NULL`` — global. ``OAuth2Client.workspace_id`` (issue
  #169) is nullable so per-workspace variants remain a future extension,
  but the v1 SDK uses the global client only.
- ``client_secret_hash=''`` and ``token_endpoint_auth_method='none'`` —
  public client per RFC 8628. ``oauth2_server.py`` registers ``'none'``
  in ``_TOKEN_ENDPOINT_AUTH_METHODS``.
- ``grant_types=['urn:ietf:params:oauth:grant-type:device_code',
  'refresh_token']`` only. ``authorization_code`` is intentionally
  absent so that this public client cannot ever drive the auth-code
  flow (which would require PKCE plumbing on the SDK side and is out
  of scope for v1).
- ``response_types=[]`` — no auth-code response.
- ``scope='memory:read memory:write'`` — ``memory:admin`` is
  intentionally excluded (narrowing-first ordering per #608 D1,
  ``mcp_scopes.py``). The seeded client therefore never receives admin
  by default. Admin-bearing clients must be registered through the
  admin endpoints with an explicit non-default scope.

Refresh-token rotation (verified at this revision):
    ``RefreshTokenGrant.revoke_old_credential`` in
    ``backend/src/auth/oauth2_server.py`` revokes BOTH the old
    access_token AND the old refresh_token on every refresh, enforcing
    rotation per RFC 6819 §5.2.2.3. Public-client refresh issuance for
    ``kagura-cli`` is therefore safe by construction. If this rotation
    is ever disabled, this assumption MUST be re-verified before
    leaving ``kagura-cli`` in production.

Idempotency:
    ``ON CONFLICT (client_id) DO NOTHING`` makes re-runs safe and
    preserves any local modifications (operator-edited ``client_name``,
    ``redirect_uris``, etc.). Re-running this migration never
    overwrites or duplicates the row.

Downgrade policy (DELETE the seeded row + cascade dependents):
    ``downgrade()`` removes the ``kagura-cli`` row. The foreign keys on
    ``oauth_tokens.client_id`` (from baseline migration
    ``157247e0df86``) and ``oauth_device_codes.client_id`` (from
    ``d08_536_device_code_grant``) are both ``ON DELETE CASCADE``, so
    dependent tokens and device codes are cleaned up atomically.

    A no-op downgrade was the original instinct ("preserve tokens"),
    but it breaks the alembic chain: ``d04_519_oauth_owner_nullable``
    sits earlier in the chain and its ``downgrade()`` runs
    ``ALTER COLUMN owner_id SET NOT NULL``. If this seed row (with
    ``owner_id=NULL``) is left in place during a deep downgrade, that
    ALTER fails — every ``test_downgrade_to_base_and_upgrade``-style
    chain rolling past d04_519 would crash. Deleting the row here keeps
    the chain reversible.

    Operational impact in production:
    - Active SDK sessions using ``kagura-cli`` tokens will be
      invalidated the moment this downgrade lands. Operators rolling
      back should announce the impending SDK auth outage to users
      ahead of time.
    - Re-running ``upgrade`` immediately afterwards re-seeds the row,
      but does NOT reissue tokens — users must re-run
      ``kagura auth login``. This matches the rollback discipline for
      any auth-schema change.

Revision ID: e10_624_seed_kagura_cli_client
Revises: e09_608_dcr_default_narrow
"""

import sqlalchemy as sa

from alembic import op

revision = "e10_624_seed_kagura_cli_client"
down_revision = "e09_608_dcr_default_narrow"
branch_labels = None
depends_on = None


# Hard-coded on purpose: an Alembic migration is a snapshot of intent at
# revision time. Importing the runtime constants from
# ``auth.mcp_scopes`` would couple the seed shape to whatever that file
# happens to contain the day someone runs ``alembic upgrade head`` years
# later, which is the opposite of what migrations are for. The values
# below match the Issue #624 design contract — if the design changes,
# write a new migration; do not edit this file. Tests in
# ``backend/tests/test_e10_624_seed_kagura_cli_migration.py`` pin these
# constants against the issue spec so silent edits will fail loud.
_CLIENT_ID = "kagura-cli"
_CLIENT_NAME = "Kagura Memory CLI"
_SCOPE = "memory:read memory:write"
_REDIRECT_URIS_JSON = '["urn:ietf:wg:oauth:2.0:oob", "http://127.0.0.1:0/"]'
_GRANT_TYPES_JSON = '["urn:ietf:params:oauth:grant-type:device_code", "refresh_token"]'
_RESPONSE_TYPES_JSON = "[]"


def upgrade() -> None:
    op.execute(
        sa.text(
            """
            INSERT INTO oauth_clients (
                client_id,
                client_secret_hash,
                client_name,
                owner_id,
                workspace_id,
                redirect_uris,
                grant_types,
                response_types,
                scope,
                token_endpoint_auth_method,
                provider
            ) VALUES (
                :client_id,
                '',
                :client_name,
                NULL,
                NULL,
                CAST(:redirect_uris AS JSON),
                CAST(:grant_types AS JSON),
                CAST(:response_types AS JSON),
                :scope,
                'none',
                'custom'
            )
            ON CONFLICT (client_id) DO NOTHING
            """
        ).bindparams(
            client_id=_CLIENT_ID,
            client_name=_CLIENT_NAME,
            redirect_uris=_REDIRECT_URIS_JSON,
            grant_types=_GRANT_TYPES_JSON,
            response_types=_RESPONSE_TYPES_JSON,
            scope=_SCOPE,
        )
    )


def downgrade() -> None:
    # See module docstring "Downgrade policy" for rationale.
    op.execute(
        sa.text("DELETE FROM oauth_clients WHERE client_id = :client_id").bindparams(
            client_id=_CLIENT_ID
        )
    )
